### ISSUE TITLE
1.0.0 tracking

### ISSUE THREAD

**Issue by zackschuster** [zackschuster/vfx#11]
Items are in order of planned execution:
- [x] Build out unit tests (again) #5
- [ ] Bundle with rollup (precursor to self-hosting) #13 
- [ ] Fully self-host #10
- [ ] File watching #9
- [ ] Incremental builds #12 
- [ ] Support Node.js as a compile target #14 
- [ ] Support TypeScript projects #15

**Comment by zackschuster** [comment]
Some background:

Recently I finished a full rewrite of VFX to solve a few issues, mainly a) kludgy, hard-to-maintain code, b) horribly inefficient control flow, and c) poor dependency management. As a result, I ended up changing some of the behavior and coming up with a clearer focus for what I'd like VFX to do.

So at this point I've finished the main body of work and I think things are pretty stable (yay!). Now it's on to feature additions and general maintenance work. I'm really excited for the future because I think I've done some cool things here (#humblebrag) and I'm hoping people can get some use out of it. Or, at the very least, I have a tool that will make my life a lot easier. And all it took was almost a year of effort! ❤️
